name: ROS Pre-Release Test
on: [push]

env:
  CONFIG_URL: https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml
  REPO_NAME: rosflight

jobs:
  prerelease:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rosdistro: [kinetic, melodic]
        include:
          - rosdistro: kinetic
            os_name: ubuntu
            os_code_name: xenial
            arch: amd64
            catkin_branch: kinetic-devel
          - rosdistro: melodic
            os_name: ubuntu
            os_code_name: bionic
            arch: amd64
            catkin_branch: noetic-devel
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          path: ws/src/${{ github.repository }}
      - uses: actions/setup-python@v1
        with:
          python-version: '2.7'
      - name: Install ROS Buildfarm
        run: |
          python -m pip install --upgrade pip
          pip install ros_buildfarm
      - uses: actions/checkout@v2
        with:
          repository: ros/catkin
          ref: ${{ matrix.catkin_branch }}
          path: catkin
      - name: Generate devel script
        run: |
          generate_devel_script.py $CONFIG_URL ${{ matrix.rosdistro }} default $REPO_NAME ${{ matrix.os_name }} ${{ matrix.os_code_name }} ${{ matrix.arch }} > devel_job.sh
      - name: Run devel script
        env:
          ABORT_ON_TEST_FAILURE: 1
        run: |
          sh devel_job.sh -y
